CREATE TABLE IF NOT EXISTS users (
  id       SERIAL PRIMARY KEY,
  login    VARCHAR(50) UNIQUE,
  email    VARCHAR(50) UNIQUE,
  password TEXT,
  score    INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cards (
  id  SERIAL PRIMARY KEY,
  url VARCHAR(100) UNIQUE
);